from typing import List
from app.services.base import BaseService
from app.models.base import PyObjectId
from app.models.audit_log import AuditLog
from app.repositories.audit_log import AuditLogRepository


class AuditLogService(BaseService[AuditLog, AuditLogRepository]):
    """
    Business Service for managing audit logs and modifications history.
    Delegates database access operations directly to the AuditLogRepository.
    """
    def __init__(self, audit_log_repository: AuditLogRepository):
        super().__init__(audit_log_repository)

    async def find_by_user_id(
        self,
        user_id: PyObjectId,
        skip: int = 0,
        limit: int = 100
    ) -> List[AuditLog]:
        """
        Retrieve audit logs generated by a specific administrator.
        Reuses repository.find_by_user_id().
        """
        return await self.repository.find_by_user_id(
            user_id=user_id,
            skip=skip,
            limit=limit
        )

    async def find_by_entity(
        self,
        entity_type: str,
        entity_id: str,
        skip: int = 0,
        limit: int = 100
    ) -> List[AuditLog]:
        """
        Retrieve modifications history for a specific database entity.
        Reuses repository.find_by_entity().
        """
        return await self.repository.find_by_entity(
            entity_type=entity_type,
            entity_id=entity_id,
            skip=skip,
            limit=limit
        )
