from typing import Annotated, List
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from bson import ObjectId

from app.services.audit_log import AuditLogService
from app.schemas.audit_log import AuditLogCreate, AuditLogResponse
from app.dependencies.services import get_audit_log_service
from app.dependencies.auth import require_admin
from app.models.employee import Employee
from app.models.audit_log import AuditLog
from app.models.base import PyObjectId

router = APIRouter(prefix="/audit_logs", tags=["AuditLogs"])


class DeleteAuditResponse(BaseModel):
    success: bool


@router.post("", response_model=AuditLogResponse, status_code=status.HTTP_201_CREATED)
@router.post("/", response_model=AuditLogResponse, status_code=status.HTTP_201_CREATED, include_in_schema=False)
async def create_audit_log(
    request: AuditLogCreate,
    admin_user: Annotated[Employee, Depends(require_admin())],
    audit_log_service: Annotated[AuditLogService, Depends(get_audit_log_service)]
) -> AuditLog:
    """
    Create a new audit log record.
    Admin privilege required.
    """
    return await audit_log_service.create(request)


@router.get("", response_model=List[AuditLogResponse])
@router.get("/", response_model=List[AuditLogResponse], include_in_schema=False)
async def list_audit_logs(
    admin_user: Annotated[Employee, Depends(require_admin())],
    audit_log_service: Annotated[AuditLogService, Depends(get_audit_log_service)],
    skip: int = 0,
    limit: int = 100
) -> List[AuditLog]:
    """
    Retrieve all audit logs with pagination support.
    Admin privilege required.
    """
    return await audit_log_service.get_many({}, skip=skip, limit=limit)


@router.get("/user/{user_id}", response_model=List[AuditLogResponse])
async def get_audit_logs_by_user(
    user_id: str,
    admin_user: Annotated[Employee, Depends(require_admin())],
    audit_log_service: Annotated[AuditLogService, Depends(get_audit_log_service)],
    skip: int = 0,
    limit: int = 100
) -> List[AuditLog]:
    """
    Retrieve all audit logs generated by a specific user.
    Admin privilege required.
    """
    if not ObjectId.is_valid(user_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid user ID format"
        )
    user_oid = PyObjectId(user_id)
    return await audit_log_service.find_by_user_id(user_oid, skip=skip, limit=limit)


@router.get("/entity/{entity_type}/{entity_id}", response_model=List[AuditLogResponse])
async def get_audit_logs_by_entity(
    entity_type: str,
    entity_id: str,
    admin_user: Annotated[Employee, Depends(require_admin())],
    audit_log_service: Annotated[AuditLogService, Depends(get_audit_log_service)],
    skip: int = 0,
    limit: int = 100
) -> List[AuditLog]:
    """
    Retrieve all audit logs modifying a specific entity type and entity ID.
    Admin privilege required.
    """
    # Note: entity_id could be ObjectId or standard string (e.g. employee code/config key)
    # We pass it as string to service directly
    return await audit_log_service.find_by_entity(
        entity_type=entity_type,
        entity_id=entity_id,
        skip=skip,
        limit=limit
    )


@router.get("/{log_id}", response_model=AuditLogResponse)
async def get_audit_log(
    log_id: str,
    admin_user: Annotated[Employee, Depends(require_admin())],
    audit_log_service: Annotated[AuditLogService, Depends(get_audit_log_service)]
) -> AuditLog:
    """
    Retrieve details of a specific audit log record by ID.
    Admin privilege required.
    """
    if not ObjectId.is_valid(log_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid audit log ID format"
        )
    log = await audit_log_service.get_by_id(log_id)
    if not log:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Audit log record not found"
        )
    return log


@router.delete("/{log_id}", response_model=DeleteAuditResponse)
async def delete_audit_log(
    log_id: str,
    admin_user: Annotated[Employee, Depends(require_admin())],
    audit_log_service: Annotated[AuditLogService, Depends(get_audit_log_service)]
) -> dict[str, bool]:
    """
    Delete a specific audit log record.
    Admin privilege required.
    """
    if not ObjectId.is_valid(log_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid audit log ID format"
        )
    success = await audit_log_service.delete(log_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Audit log record not found"
        )
    return {"success": True}
