from enum import Enum


class AuditAction(str, Enum):
    UPDATE_KPI_RULE = "UPDATE_KPI_RULE"
    UPDATE_REWARD_RULE = "UPDATE_REWARD_RULE"
    CREATE_EMPLOYEE = "CREATE_EMPLOYEE"
    DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
    BLACKLIST_CUSTOMER = "BLACKLIST_CUSTOMER"
