from typing import List, Optional
from motor.motor_asyncio import AsyncIOMotorCollection
from app.repositories.base import BaseRepository
from app.models.base import PyObjectId
from app.models.audit_log import AuditLog
from app.schemas.audit_log import AuditLogCreate


class AuditLogRepository(BaseRepository[AuditLog, AuditLogCreate, None]):
    """
    Concrete Repository class for executing operations on the 'audit_logs' collection.
    """
    def __init__(self, collection: AsyncIOMotorCollection):
        super().__init__(collection, AuditLog)

    async def find_by_user_id(
        self,
        user_id: PyObjectId,
        skip: int = 0,
        limit: int = 100
    ) -> List[AuditLog]:
        """Retrieve audit logs generated by a specific administrator, sorted newest first."""
        return await self.find_many(
            filter={"user_id": user_id},
            skip=skip,
            limit=limit,
            sort=[("created_at", -1)]
        )

    async def find_by_entity(
        self,
        entity_type: str,
        entity_id: str,
        skip: int = 0,
        limit: int = 100
    ) -> List[AuditLog]:
        """Retrieve modifications history for a specific database entity, sorted newest first."""
        return await self.find_many(
            filter={
                "entity_type": entity_type,
                "entity_id": entity_id
            },
            skip=skip,
            limit=limit,
            sort=[("created_at", -1)]
        )
